clc; clear all; close all;

%% — generate OFDM symbol with freq/timing offset and gain —
function [rx_sym, txSym] = genOFDMSymbol(n_fft, n_sc, cp, gain, fo, Toff, n_sym)
    halfSc = n_sc/2;
    
    txSym_matrix = zeros(n_sc, n_sym);
    txCP_total = zeros((n_fft + cp) * n_sym, 1);

    for k = 1:n_sym
        % random QPSK for current symbol
        sym_data = (2*randi([0,1],n_sc,1)-1) + ...
                   1j*(2*randi([0,1],n_sc,1)-1);
        sym_data = sym_data / sqrt(2);
        
        txSym_matrix(:, k) = sym_data;

        % place in FFT bins
        txFreq = zeros(n_fft,1);
        txFreq(end-halfSc+1:end) = sym_data(1:halfSc);
        txFreq(1:halfSc)         = sym_data(halfSc+1:end);

        % IFFT - no n_fft scaling, matches toolbox convention
        txTime = ifft(txFreq);

        % add CP
        txCP   = [txTime(end-cp+1:end); txTime];
        
        % Place in the overall time-domain array
        idx_start = (k-1) * (n_fft + cp) + 1;
        idx_end   = k * (n_fft + cp);
        txCP_total(idx_start:idx_end) = txCP;
    end
    
    % Flatten txSym into a single column vector for comparison
    txSym = txSym_matrix(:);

    % apply gain
    txCP_total = txCP_total / gain;

    % apply frequency offset continuously across all symbols
    % matches C++: angle = 2*pi*fo*(n+Toff)
    n          = (0:length(txCP_total)-1)';
    txCP_total = txCP_total .* exp(1j * 2 * pi * -fo .* (n + Toff));

    rx_sym = single(txCP_total);
end

%% — custom reference OFDMDemod ———————————————————————————
function rxSym = OFDMDemod_ref(rx_signal, params, n_sym)
    n_fft = double(params.n_fft);
    n_sc  = double(params.n_sc);
    cp    = double(params.cp);
    fo    = double(params.fo);
    pos   = double(params.pos);
    gain  = double(params.gain);
    lte   = params.lte;
    
    if lte == 0
        dc = 0;
    else
        dc = 1;
    end

    n      = (0:length(rx_signal)-1)';
    phase  = 2.0*pi*(fo).*(n+pos);
    rx_rot = single(rx_signal) .* single(exp(1j*phase));

    % apply gain
    rx_rot = rx_rot * single(gain);

    rxSym = zeros(n_sc * n_sym, 1, 'single');
    halfSc = n_sc/2;

    for k = 1:n_sym
        % Extract current symbol samples
        idx_start = (k-1) * (n_fft + cp) + 1;
        idx_end   = k * (n_fft + cp);
        sym_samples = rx_rot(idx_start:idx_end);

        % CP fraction window
        fftStart = fix(cp * 0.5);
        symOff   = cp - fftStart;
        part1    = sym_samples(cp+(1:n_fft-symOff));
        part2    = sym_samples(cp-symOff+1:cp);
        R_fft_in = [part1(:); part2(:)];

        % FFT
        R_fft = fft(R_fft_in);

        % subcarrier extraction
        lower = R_fft(end-halfSc+1:end);
        upper = R_fft(dc+1:halfSc+dc);
        
        % Place into flattened rx array
        rxSym((k-1)*n_sc + 1 : k*n_sc) = [lower(:); upper(:)];
    end
end

function write_config(params, filename)
    % Open file for writing
    fileID = fopen(filename, 'w');
    if fileID == -1
        error('Could not open %s for writing.', filename);
    end

    % Write header and comments
    fprintf(fileID, '# Configuration File\n');
    fprintf(fileID, '# Generated by MATLAB\n\n');
    
    % Convert boolean to 1 or 0 for easier C parsing
    fprintf(fileID, 'lte %d\n', uint8(params.lte)); 
    fprintf(fileID, 'scs %u\n', uint16(params.scs));
    fprintf(fileID, 'n_fft %u\n', uint16(params.n_fft));
    fprintf(fileID, 'n_sc %u\n', uint16(params.n_sc));
    fprintf(fileID, 'cp %u\n', uint16(params.cp));
    
    fprintf(fileID, 'gain %f\n', double(params.gain));
    fprintf(fileID, 'fo %f\n', double(params.fo_hz));
    
    fprintf(fileID, 'to %u\n', uint64(params.Toff)); 
    fprintf(fileID, 'threshold %f\n', double(params.thresh));

    fclose(fileID);
end

function write_complex_bin(data, filename)
    binID = fopen(filename, 'wb');
    if binID == -1
        error('Could not open %s for writing.', filename);
    end
    
    % Interleave Real and Imaginary parts: [Re(1), Im(1), Re(2), Im(2)...]
    num_elements = length(data);
    interleaved_data = zeros(1, 2 * num_elements);
    interleaved_data(1:2:end) = real(data);
    interleaved_data(2:2:end) = imag(data);
    
    % Write out as double-precision floating point
    fwrite(binID, interleaved_data, 'double');
    fclose(binID);
end

%% — configs ——————————————————————————————————————————————
% {Nfft, Nsc, cp, SCS}
configs = {
    128,  72,   9,   15;
    256,  132,  18,  15;
    512,  252,  36,  15;
    1024, 516,  72,  15;
    2048, 1020, 144, 15;
    4096, 3300, 288, 15;
};

%% — sweep values —————————————————————————————————————————
gainList = [1.0, 2.0, 0.5];          % rx gain
foHzList = [0, 100, -100];           % freq offset Hz
ToffList = [0, 5, 10];               % timing offset samples
n_sym    = 14;                       % Number of symbols (1 slot)

%% — size dependent threshold —————————————————————————————
threshMap = containers.Map(...
    {128, 256, 512, 1024, 2048, 4096},...
    {1e-4, 1e-4, 5e-4, 1e-3, 2e-3, 5e-3});

%% — result storage ———————————————————————————————————————
results = {};
nPass   = 0;
nFail   = 0;
testIdx = 0;

fprintf('\n%-5s  %-4s  %-7s  %-5s  %-3s  %-8s  %-6s\n',...
    'n_fft','gain','fo_hz','Toff','scs','Diff','Pass');
fprintf('%s\n', repmat('-',1,75));

for i = 1:size(configs,1)
    n_fft  = configs{i,1};
    n_sc   = configs{i,2};
    cp     = configs{i,3};
    scs    = configs{i,4};
    thresh = threshMap(n_fft);
    fs     = scs * 1e3 * n_fft;  % sample rate Hz

    % Randomly pick from lists
    gain  = gainList(randi(length(gainList)));
    fo_hz = foHzList(randi(length(foHzList)));
    Toff  = ToffList(randi(length(ToffList)));

    fo_normalized = fo_hz / fs;
    testIdx = testIdx + 1;

    % — generate 14 symbols —————————————————————
    [rx_sym, txSym] = genOFDMSymbol(...
        n_fft, n_sc, cp, gain, ...
        fo_normalized, Toff, n_sym);

    % — params ————————————————————————————————
    params.lte    = 0;
    params.scs    = scs;
    params.n_fft  = double(n_fft);
    params.n_sc   = double(n_sc);
    params.cp     = double(cp);
    params.fo_hz  = double(fo_hz);
    params.fo     = double(fo_normalized);
    params.pos    = double(Toff);
    params.Toff   = double(Toff);
    params.gain   = double(gain);
    params.thresh = double(thresh);

    % — custom reference ——————————————————————
    try
        refSym = OFDMDemod_ref(rx_sym, params, n_sym);
    catch e
        fprintf('REF ERR n_fft=%d: %s\n', n_fft, e.message);
        nFail = nFail+1; continue;
    end

    % — compare vs txSym ——————————————————————
    diff  = max(abs(single(refSym) - single(txSym)));

    % — pass/fail —————————————————————————————
    passed = diff < thresh;
    if passed, nPass=nPass+1; else, nFail=nFail+1; end
    
    fprintf('%5d, %4.2f, %7.2f, %5.2f, %3d, %8.2e, ', n_fft, gain, fo_hz, Toff, scs, diff)
    if ~passed
        fprintf('Fail\n');
    else
        fprintf('Pass\n');
    end

    % — store —————————————————————————————————
    if passed
        % Generate a readable filename based on frequency
        fname = sprintf('ofdm_demod_%d_MHz', round(fs / 1e6));

        % Construct paths using the filename
        configPath = fullfile('test_vectors/configs', [fname, '.txt']);
        inputPath  = fullfile('test_vectors/inputs',  [fname, '.bin']);
        refPath    = fullfile('test_vectors/refs',    [fname, '.bin']);
        
        if ~exist('test_vectors/configs', 'dir'), mkdir('test_vectors/configs'); end
        if ~exist('test_vectors/inputs', 'dir'),  mkdir('test_vectors/inputs');  end
        if ~exist('test_vectors/refs', 'dir'),    mkdir('test_vectors/refs');    end

        write_config(params, configPath);
        write_complex_bin(rx_sym, inputPath);
        write_complex_bin(txSym, refPath);
    end
end

%% — summary ——————————————————————————————————————————————
fprintf('\n%s\n', repmat('=',1,75));
fprintf('Total:%d  Pass:%d  Fail:%d  PassRate:%.1f%%\n',...
    testIdx, nPass, nFail, 100*nPass/testIdx);
fprintf('%s\n', repmat('=',1,75));